import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import MakeDesignBetter from '../components/MakeDesignBetter'
import WhatWeOffer from '../components/WhatWeOffer'
import WhyChooseUs from '../components/WhyChooseUs'
import YouImagineWeCreate from '../components/YouImagineWeCreate'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
      <MakeDesignBetter/>
      <YouImagineWeCreate/>
      <WhyChooseUs/>
      <WhatWeOffer/>

     
    </div>
  )
}
